---
- hosts: all !containers
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: check if a reboot is required
      shell: "[ -f /var/run/reboot-required ]"
      failed_when: False
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: user_message

  handlers:
    - name: user_message
      debug:
        msg: "Reboot required"
