---
- hosts: all
  become: true

  tasks:
    - name: Wait for sudo
      wait_for:
        connect_as_sudo_user: true

    - name: install packages
      apt:
        state: present
        name:
          - tcsh
          - htop
