---
- hosts: all
  tasks:
  - package:
      name: "httpd"
      state: present
    when: ansible_facts["distribution"] == "RedHat"
  - package:
      name: "apache2"
      state: present
    when: ansible_facts["distribution"] == "Ubuntu"