---
- hosts: all
  become: yes
 
  tasks:
  - name: Add repository
    ansible.builtin.yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
 
  - name: Installs nginx web server
    yum:
      name: nginx
      state: present
    notify:
    - start nginx
  handlers:
  - name: start nginx
    service:
      name: nginx
      state: started
