---
- hosts: AppServer
  become: yes
  tasks:
  - name: Installs nginx web server
    yum:
      name: nginx
      state: present
    notify:
    - start nginx
  handlers:
  - name: start nginx
    service:
      name: nginx
      state: started
