---
- hosts: all
  tasks:
    - name: Get list of IP addresses
      shell: ip a
      register: ip_addresses

    - name: Print IP address information
      debug:
        msg: "{{ item }}"
      loop: "{{ ip_addresses.stdout_lines }}"
      when: not item | match('inet 169')
