---
- hosts: all
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install netaddr module
      pip:
        name: netaddr
        state: present

    - name: Get IP address information
      command: ip -o -4 addr show
      register: ip_info

    - name: Print IP address information
      debug:
        msg: "{{ item }}"
      when: item | ipaddr('address') != "169.0.0.0/8"
      with_items: "{{ ip_info.stdout_lines }}"
