---
- hosts: all
  tasks:
    - name: Get IP address information
      command: ip -o -4 addr show
      register: ip_info

    - name: Print IP address information
      debug:
        msg: "{{ item }}"
      when: not item | match('inet 169')
      with_items: "{{ ip_info.stdout_lines }}"
